language: python
python:
- '2.7'
sudo: false
cache:
  directories:
  - "~/.platformio"
env:
  - PIO_ENV=emonesp
  - PIO_ENV=smartplug
  - PIO_ENV=wifirelay
  - PIO_ENV=hpmon
  - PIO_ENV=esp12e
  - PIO_ENV=pvrouter
install:
- pip install -U platformio
- platformio platform install espressif8266
script:
- platformio --version
- platformio run -e $PIO_ENV
